# SeriousRP | Owner : stan1712 
Version: VERSION NOT SET PLEASE SET ConfigFix TO true
ConfigFix: true
Prefix: FireEquipement

#Core messages
Core:
  NoPerms: "You don't have the permission !"
  HelpMsg:
    Help: "Need help ? Type /firequip help"
    VersionHelp: "Plugin's version ? Type /firequip version"
    DHelp: "Shows a help page"
    DVersion: "Be able to know plugin's version"
    DGive: "Be able to give yourself an item"
  GiveMsg:
    Home: "What item do you want ?"
    Hose: "You get an Fire Hose"
    Pump: "You get a pump"
    Extinguisher: "You get an extinguisher"
    
Equipment:
  Hose:
    displayName: "Fire Hose"
    range: 5
  Pump:
    displayName: "Water Pump"
    range: 4
  Extinguisher:
    displayName: "Extinguisher"
    range: 2