name: FireEquipment
description: Roleplay Plugin for Firefigther
author: stan1712
version: 1.5
main: fr.stan1712.firequip.Main

commands:
  firequip:
    permission: firequip.info
  equip:
    permission: firequip.tools.give
    